hists:
	./hists.jl
convert:
	./convert.py results/hists/bdt_sig_bg.csv results/hists/bdt_sig_bg.root
	./convert.py results/hists/top_mass.csv results/hists/top_mass.root
	./convert.py results/hists/ljet_eta.csv results/hists/ljet_eta.root
	./convert.py results/hists/mtw.csv results/hists/mtw.root
	./convert.py results/hists/C.csv results/hists/C.root
